@file:Suppress("DEPRECATION")

import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidMultiplatformLibrary)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinx.serialization)
    alias(libs.plugins.kotlin.ksp)
    alias(libs.plugins.androidx.room)
    alias(libs.plugins.koin.compiler)
}

/**
 * API keys are read from `local.properties` (gitignored) or the environment, and
 * emitted as a Kotlin object. `commonMain` cannot see Android's BuildConfig, so
 * codegen is the portable way to get them into shared code.
 *
 * A missing key produces an empty string; the matching provider then reports
 * `isEnabled = false` and the aggregator skips it, so the project still builds
 * and runs with no keys configured at all.
 */
val apiKeyNames = listOf(
    "PEXELS_API_KEY",
    "UNSPLASH_ACCESS_KEY",
)

val generateApiKeys by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/apikeys/commonMain/kotlin")
    val localPropsFile = rootProject.file("local.properties")
    val resolved = apiKeyNames.associateWith { name ->
        val fromProps = if (localPropsFile.exists()) {
            java.util.Properties()
                .apply { localPropsFile.inputStream().use { load(it) } }
                .getProperty(name)
        } else null
        (fromProps ?: System.getenv(name) ?: "").trim()
    }

    inputs.property("apiKeys", resolved.toSortedMap().toString())
    outputs.dir(outputDir)

    doLast {
        val dir = outputDir.get().asFile.resolve("com/google/wallpaperapp/data/remote")
        dir.mkdirs()
        val constants = resolved.entries.joinToString("\n") { (name, value) ->
            val constName = when (name) {
                "PEXELS_API_KEY" -> "PEXELS"
                "UNSPLASH_ACCESS_KEY" -> "UNSPLASH"
                else -> name
            }
            val escaped = value.replace("\\", "\\\\").replace("\"", "\\\"")
            "    const val $constName: String = \"$escaped\""
        }
        dir.resolve("ApiKeys.kt").writeText(
            """
            |// Generated by the `generateApiKeys` Gradle task. Do not edit.
            |package com.google.wallpaperapp.data.remote
            |
            |object ApiKeys {
            |$constants
            |}
            |
            """.trimMargin()
        )
    }
}

kotlin {
    android {
        namespace = "com.google.wallpaperapp.composeapp"
        compileSdk = libs.versions.android.compileSdk.get().toInt()
        minSdk = libs.versions.android.minSdk.get().toInt()
        androidResources.enable = true

        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }

    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
        }
    }

    sourceSets {
        androidMain.dependencies {
            implementation(compose.preview)
            implementation(compose.uiTooling)
            implementation(libs.androidx.activity.compose)
            implementation(libs.ktor.client.okhttp)

        }
        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.ui)
            implementation(compose.components.resources)
            implementation(compose.components.uiToolingPreview)
            implementation(libs.androidx.lifecycle.viewmodelCompose)
            implementation(libs.androidx.lifecycle.runtimeCompose)

            //Material Icons
            implementation(compose.materialIconsExtended)

            //ImageLoading
            implementation(libs.landscapist.coil3)
            implementation(libs.landscapist.animation)

            //Navigation
            implementation(libs.navigation.compose)
            implementation(libs.viewmodelNavigation3)


            //Pagination
            implementation(libs.paging.multiplatform.common)
            implementation(libs.paging.multiplatform.compose.common)

            //Koin
            implementation(project.dependencies.platform(libs.koin.bom))
            implementation(libs.bundles.koin.di)
            api(libs.koin.annotations)

            //Ktor
            implementation(libs.bundles.ktor.networking)

            //Room
            implementation(libs.androidx.room.runtime)
            implementation(libs.androidx.sqlite.bundled)
            implementation(libs.androidx.room.paging)


        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.coroutines.test)
        }

        nativeMain.dependencies {
            implementation(libs.ktor.client.darwin)
        }

        // KSP Common sourceSet
        sourceSets.named("commonMain").configure {
            kotlin.srcDir("build/generated/ksp/metadata/commonMain/kotlin")
            kotlin.srcDir(generateApiKeys)
        }
    }

    targets.configureEach {
        compilations.configureEach {
            compileTaskProvider.get().compilerOptions {
                freeCompilerArgs.add("-Xexpect-actual-classes")
            }
        }
    }

}



dependencies {
    add("kspAndroid", libs.androidx.room.compiler)
    add("kspIosArm64", libs.androidx.room.compiler)
    add("kspIosSimulatorArm64", libs.androidx.room.compiler)
}

// Trigger Common Metadata Generation from Native tasks
tasks.matching { it.name.startsWith("ksp") && it.name != "kspCommonMainKotlinMetadata" }.configureEach {
    dependsOn("kspCommonMainKotlinMetadata")
}

// KSP reads commonMain sources, so the generated ApiKeys must exist first.
tasks.matching { it.name.startsWith("ksp") }.configureEach {
    dependsOn(generateApiKeys)
}

room {
    schemaDirectory("$projectDir/schemas")
}

configure<org.koin.compiler.plugin.KoinGradleExtension> {
    // ponytail: platform DI still comes from expect/actual + DSL modules; re-enable once that is modeled with Koin annotations.
    compileSafety.set(false)
}
